[live snapshot] make snapshot name from const char* to char*
This will fix a build error as below on some platforms.

migration.c: In function ‘savevm_start_outgoing_migration’:
migration.c:383:17: error: initialization discards ‘const’ qualifier from pointer target type [-Werror]
cc1: all warnings being treated as errors
(cherry picked from commit 49efc432881b313906d2123526086c57007df398)